version: "3"
services:
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    volumes:
      - data-files:./
    depends_on:
      - db
    expose:
      - "5000"
  frontend:
    build: ./frontend
    container_name: ./frontend
    restart: unless-stopped
    depends_on:
      - api
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - api
      - frontend
  database:
    image: postgres:12-alpine
    container_name: database
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file: ./database/db.conf

volumes:
  db-data
  