version: "3"
services:
    database:
        image: postgres:12-alpine
        container_name: database
        restart: unless-stopped
        volumes:
            - db-data:/var/lib/postgresql/data 
        expose:
            - "5432"
        env_file: ./database/db.conf
    datastore:
        image: mongo:latest
        container_name: datastore
        restart: unless-stopped
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=super_secret_password
            - ALGORITHM=HS256
        expose:
            - "27017"
        volumes:
            - datastore-data:/data/db 
    api:
        build: ./api
        container_name: api
        restart: unless-stopped
        depends_on:
            - database
            - datastore
        expose:
            - "8000"
        environment:
            - SECRET_KEY=super_secret_key
            - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://touchscreen:super_secret_password@database:5432/touchscreenDB
            - MONGO_DATABASE_HOST=mongodb://root:super_secret_password@datastore:27017
    frontend:
        build: ./frontend
        container_name: frontend
        restart: unless-stopped
        depends_on:
            - api
        expose:
            - "8080"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
        ports:
            - 80:80
        depends_on:
            - api



volumes:
    db-data:
    datastore-data: